compose:
   zookeeper:
     image: jplock/zookeeper
   hdfs:
     image: chalimartines/cdh5-pseudo-distributed
   marathon:
     image: mesosphere/marathon
     command: [--master, "local", --zk, "zk://localhost:2181/marathon"]
   chronos:
     image: mesosphere/chronos
   #cassandra:
   #  image: cassandra
  cassandra:
    image: cassandra:3.2
    environment:
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
      - CASSANDRA_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_START_RPC=true

build:
  image: lensa/pyspark:ubuntu-pkgs-2-3-spark-1.6.0-hdfs-client-cdh5.5.1-java-8-mesos-0.25.0-0.2.70-ubuntu-15.04
  environment:
    - ZOOKEEPER_PATH=/usr/share/java
    - ZOOKEEPER_HOST=localhost
    - HDFS_HOST=localhost
    - CASSANDRA_TEST_HOST=127.0.0.1
    - CASSANDRA_TEST_PORT=9042
  commands:
    - sleep 5
    - hdfs dfs -ls hdfs://localhost/
    - echo 'spark.jars.packages datastax:spark-cassandra-connector:1.6.0-M1-s_2.10' >> $SPARK_HOME/conf/spark-defaults.conf
    - python setup.py test
