compose:
  zookeeper:
    image: jplock/zookeeper
  mesos-master:
    image: mesosphere/mesos-master:0.26.0-0.2.145.ubuntu1404
    environment:
      - MESOS_ZK=zk://localhost:2181/mesos
      - MESOS_HOSTNAME=localhost
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
  mesos-slave:
    image: mesosphere/mesos-slave:0.26.0-0.2.145.ubuntu1404
    environment:
      - MESOS_MASTER=zk://localhost:2181/mesos
      - MESOS_HOSTNAME=localhost
      - MESOS_CONTAINERIZERS=docker,mesos
    volumes:
      - /tmp/mesos:/tmp/mesos
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  marathon:
    image: mesosphere/marathon
    environment:
      - MARATHON_MASTER=zk://localhost:2181/mesos
  chronos:
    image: mesosphere/chronos:chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.26.0-0.2.145.ubuntu1404
    command: ["/usr/bin/chronos", --http_port, "4400", --master, "zk://localhost:2181/mesos", --zk_hosts, "localhost:2181"]
  hdfs:
    image: dockmob/hadoop:2.7.1
    command: [-t, "pseudodistributed"]
  cassandra:
    image: cassandra:3.2
    environment:
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
      - CASSANDRA_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_START_RPC=true


build:
  image: lensa/pyspark:pip-2-3-spark-1.6.0-hdfs-client-cdh5.5.1-java-8-mesos-0.26.0-0.2.145-ubuntu-15.04
  environment:
    - ZOOKEEPER_PATH=/usr/share/java
    - CASSANDRA_HOST=127.0.0.1:9042
    - ZOOKEEPER_HOST=localhost:2181
    - MARATHON_HOST=localhost:8080
    - CHRONOS_HOST=localhost:4400
  commands:
    - export HDFS_HOST=`hostname`:8020
    - echo 'spark.jars.packages datastax:spark-cassandra-connector:1.6.0-M1-s_2.10' >> $SPARK_HOME/conf/spark-defaults.conf
    - python setup.py test
