build:
  image: jplock/zookeeper
  environment:
    - ZOOKEEPER_PATH=/opt/zookeeper
  commands:
    - apk add --update python python-dev py-pip build-base openssl ca-certificates git
    - python setup.py test
