build:
  image: lensa/pyspark:ubuntu-pkgs-2-3-spark-1.6.0-hadoop-2.6-hdfs-client-cdh5.5.1-java-8-mesos-0.25.0-0.2.70-ubuntu-15.04
  environment:
    - ZOOKEEPER_PATH=/usr/share/java
  commands:
    - python setup.py test
